<?php

namespace AppBundle\Repository;


/**
 * BookRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BookRepository extends \Doctrine\ORM\EntityRepository
{

    public function findLast($limit)
    {
        return $this->getEntityManager()
                    ->createQueryBuilder()
                    ->select('b', 'a')
                    ->from('AppBundle:Book', 'b')
                    ->innerJoin('b.author', 'a')
                    ->orderBy('b.createdAt',"DESC")
                    ->setMaxResults($limit)
                    ->getQuery()
                    ->getResult();
    }

    public function findRandom($limit, $selectedBook )
    {
        $selectedID = $selectedBook->getId();
        $sql ="SELECT * from book
                WHERE book.id NOT IN (".$selectedID.")
                 ORDER BY RAND()
                 LIMIT ".$limit." ";

        //var_dump($sql);die();
        $em = $this->getEntityManager();//getDoctrine()->getManager();
        $stmt = $em->getConnection()->prepare($sql);
        $stmt->execute();

        //var_dump($stmt);die();
        return $stmt->fetchAll();
    }
}
