<?php

namespace AppBundle\Repository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
    public function findLast($identity) {
        return $this->getEntityManager()
            ->createQueryBuilder()
            ->select('user.id', 'ui')
            ->select('user.firstname', 'uf')
            ->select('user.lastname', 'ui')
            ->select('user.username', 'ui')
            ->select('user.email', 'ui')
            ->select('user.roles', 'ui')
            ->select('user.id', 'ui')
            ->select('user.id', 'ui')
            ->select('user.id', 'ui')
            ->from('AppBundle:User', 'u')
            ->setMaxResults($identity)
            ->getQuery()
            ->getResult()
            ;
    }
}
