<?php

namespace AppBundle\Repository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
    public function findUserWithCount($limit){
        return $this->getEntityManager()
            ->createQueryBuilder()
            ->select('u AS user, COUNT(b.id) AS count_borrows')
            ->from('AppBundle:user', 'u')
            ->leftJoin('u.borrows', 'b')
            ->groupBy('u.id')
            ->orderBy('u.id', 'DESC')
            ->setMaxResults($limit)
            ->getQuery()
            ->getResult()
            ;
    }
}
